React query
mrnkim/Who-Talked-About-Us pull request #1
Opened 2023-11-18 01:11 UTC by mrnkim

- 지난 번 피드백 이후 4개 commit 했습니다. 주신 세 가지 피드백 전반적으로 제대로 적용된 것인지 궁금합니다. 
- 특히 App.js, VideoIndex.js 및 Task.js ErrorBoundary의 onReset과 resetKeys를 잘 설정한 건지 궁금합니다. 
- VideoIndex.js에서 searchResults의 경우, useMutation으로 받는 data라 (GET request로부터가 아닌) onReset과 resetKeys를 설정하지 않았는데 이 경우에도 필요한 건지 궁금합니다.

2023-11-20 09:21 UTC, JWWon requested changes
Here are comments about across the project itself.

1. [Required] You need to update `package-lock.json` file by reinstalling packages with npm.
2. [Required] I already left comment about why doing comparison with optional parameters are risky  on `App.js` file, but I read same patterns across the project. Please avoid this pattern and make sure variable is not empty before compare with numeric values.
3. [Optional] Wrapping `Suspense` and `ErrorBoundary` on right upper level of each component which renders query hook would help to prevent show loading and error fallback on much bigger scope.
4. [Info] The way how you handles `form` and `input` is great, but it would be much better to handle these inputs in `uncontrolled` way. Sometimes it is required because of performance aspect, because set values of inputs in react lifecycle (by using `useState`) could cause unnecessary re-rendering and it could cause some issues if input or component is heavy.
    - You could find more details in [this article](https://www.freecodecamp.org/news/how-to-build-forms-in-react/)

2023-11-20 09:21 UTC, JWWon commented on src/api/api.js
There is one thing missing here, `pagination`.

Since data is sliced into multiple pages on `GET` method endpoints, you need to make arguments to control `page` and `page_limit` for controlling it.

For instance, `getIndexes` method can be written like below.

```typescript
interface GetIndexesParams {
  /**
   * @default 1
   */
  pages?: number;
  /**
   * @default 20
   */
  pageLimit?: number;
}

static async getIndexes({ page = 1, pageLimit = 20 }: GetIndexesParams): AxiosResponse<IndexResponse[]> {
  const config = {
    ...,
    params: { page, page_limit: pageLimit }
  }

  ...
}
```

2023-11-20 09:21 UTC, JWWon commented on src/api/api.js
> +        query: `${query}`,
```suggestion
        query,
```

2023-11-20 09:21 UTC, JWWon commented on src/App.js
> +      {indexes?.length > 0 && (
Since `App` component is not wrapped with ErrorBoundary, occasionally error could be happened and type of `indexes?.length` could be `undefined`. If it happens, application will break.

So instead of comparing number directly with optional variable, you need to wrap this condition by checking if `indexes` is not undefined value.

```suggestion
      {indexes != null && indexes.length > 0 && (
```

But better way is handling errors before rendering this section

2023-11-20 09:21 UTC, JWWon commented on src/api/api.js
After you migrate this project into typescript, you could add types about parameters and responses like upper comment.

2023-11-20 09:21 UTC, JWWon commented on src/search/SearchForm.js
> +        });
Question. What happen after it mutates search video? I couldn't see any further actions after mutation.

2023-11-20 09:21 UTC, JWWon commented on src/search/SearchForm.js
More common way to execute search with react query is not using mutation but using another useQuery hook.

```typescript
// SearchForm.ts

function SearchForm({ onSubmit }: { onSubmit: React.FormEventHandler<HTMLInputElement> }) {
  return (
    <form onSubmit={onSubmit}>
      <input name="query" placeholder="What are you looking for? (e.g., applying MAC gold highlighter)" />
      {...}
    </form>
  )
}
```

```typescript
// VideoIndex.ts

import SearchFrom from "../search/SearchForm";

function VideoIndex() {
  const [query, setQuery] = useState<string>();

  const handleSubmit = (e: React.FormEvent<HTMLInputElement>) => {
    setQuery(e.target.value);
  };

  return (
    <>
      {...}
      {query != null ? (
        <Suspense fallback={</>}>
          <ErrorBoundary fallback={</>}>
            <SearchResultList query={query} />
          </ErrorBoundary>
        </Suspense>
        ) : <SearchForm onSubmit={handleSubmit} />
      }
    </>
  );
}
```

```typescript
// SearchResultList.ts

function SearchResultList({ indexID, query }: { indexID: string; query: string }) {
  const { data, ... } = useQuery({
    queryKey: ["search"],
    queryFn: async () => axios.post(
      `${BASE_URL}/search`,
      { data: { index_id: indexID, search_options: [...], query } })
  });

  return ...
}
```

2023-11-21 20:36 UTC, mrnkim commented on src/search/SearchForm.js
> +        });
You're right. I believe then I shall change mutateAsync to mutate and async function to function.

2023-11-21 20:37 UTC, mrnkim commented on src/api/api.js
Thanks for pointing this out! I've implemented pagination for getIndexes and updated one for videos using react Query.

2023-11-28 22:28 UTC, mrnkim commented
@JWWon 
I've made the updates except for the handling form in uncontrolled way (which is not a priority as of now). Please review and let me know if you have any further questions. Thanks!

2023-11-29 06:59 UTC, JWWon approved these changes
Looks all good!! Comments I left are just an optional ones.

2023-11-29 06:59 UTC, JWWon commented on src/indexes/VideoIndex.js
> +                  {" "}
Redundant line was added here

```suggestion
```

2023-11-29 06:59 UTC, JWWon commented on src/search/SearchForm.css
> +      font-size: 0.875rem;
Wrong indent!

```suggestion
    font-size: 0.875rem;
```

2023-11-29 06:59 UTC, JWWon commented on src/indexes/VideoIndex.js
> +                  />
Rendering `SearchForm` separately by value of `finalSearchQuery` might cause unexpected rerendering. I suggest you to render this section outside of the conditional section, but if it doesn't look buggy I think we can leave it as it is for now :)

```javascript
            <div>
              <div className="videoSearchForm">
                {!finalSearchQuery && <div className="title">Search Videos</div>}
                <div className="m-auto p-3 searchFormContainer">
                  <SearchForm
                    index={currIndex}
                    setSearchQuery={setSearchQuery}
                    searchQuery={searchQuery}
                    setFinalSearchQuery={setFinalSearchQuery}
                  />
                </div>
              </div>
```

2023-11-29 21:50 UTC, merged